export {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableEmpty,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
  type TableBodyProps,
  type TableCaptionProps,
  type TableCaptionSide,
  type TableCellAlign,
  type TableCellFont,
  type TableCellProps,
  type TableCellTone,
  type TableEmptyProps,
  type TableFooterProps,
  type TableHeadProps,
  type TableHeadWidth,
  type TableHeaderProps,
  type TableProps,
  type TableRowProps,
} from './table';
